RubiksMX/Models/ErrorViewModel.cs
namespace RubiksMX.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RubiksMX/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;

namespace RubiksMX.Controllers
{
    public class CategoriasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult _3x3()
        {
            return View();
        }

        public IActionResult _4x4()
        {
            return View();
        }

        public IActionResult _5x5()
        {
            return View();
        }

        public IActionResult _6x6()
        {
            return View();
        }

        public IActionResult _7x7()
        {
            return View();
        }

    }
}

RubiksMX/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RubiksMX.Models;
using System.Diagnostics;

namespace RubiksMX.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RubiksMX/Controllers/SobreNosotrosController.cs
using Microsoft.AspNetCore.Mvc;

namespace RubiksMX.Controllers
{
    public class SobreNosotrosController : Controller
    {
        public IActionResult SobreNosotros()
        {
            return View();
        }
    }
}

RubiksMX/Views/Categorias/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
 pruebas10

RubiksMX/Views/Categorias/_3x3.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "3x3";
}
 pruebas3x3

RubiksMX/Views/Categorias/_4x4.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
    
*@

@{
  
}
4x4

RubiksMX/Views/Categorias/_5x5.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
5x5

RubiksMX/Views/Categorias/_6x6.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
6x6

RubiksMX/Views/Categorias/_7x7.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
7x7

RubiksMX/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />


 

<div class="content">
    <div class="background-img"><img src="/img/cubosolo.jpg"/></div>
    <div class="d-flex justify-content-center" style="transform: translateY(-200px)">
        <button id="scrollButton">Desplazarse hacia abajo</button>
    </div>


    <h1>Contenido Arriba</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque euismod, libero at hendrerit varius, tortor nisl tempus tellus, vel semper nunc quam ac libero.</p>
    <!-- Botón de Scroll -->
    

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque euismod, libero at hendrerit varius, tortor nisl tempus tellus, vel semper nunc quam ac libero.</p>
    <h2>Más Contenido Abajo</h2>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
    <p>Más contenido interesante...</p>
</div>
<script src="/js/site.js"></script>

RubiksMX/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rubiks MX</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFirstPageWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <header>
        <div class="">
            <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color:black;">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="~/img/logoletras.png" width="200px" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon custom-toggler-icon">
                        <i class="fas fa-bars" style="color:#fff; font-size:28px;"></i>
                    </span>
                </button>

                <style>
                    .custom-toggler-icon {
                        color: white; /* Cambia esto por el color deseado */
                    }
                </style>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: white;">
                                Categorias
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="@Url.Action("_3x3", "Categorias")">3x3</a>
                                <a class="dropdown-item" href="@Url.Action("_4x4", "Categorias")">4x4</a>
                                <a class="dropdown-item" href="@Url.Action("_5x5", "Categorias")">5x5</a>
                                <a class="dropdown-item" href="@Url.Action("_6x6", "Categorias")">6x6</a>
                                <a class="dropdown-item" href="@Url.Action("_7x7", "Categorias")">7x7</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Mas...</a>
                            </div>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="#" style="color: white;">Promociones <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="@Url.Action("SobreNosotros", "SobreNosotros")" style="color: white;">Sobre Nosotros</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
            <main role="main" class="">
                @RenderBody()
            </main>
        </div>

    </header>




    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RubiksMX/Views/SobreNosotros/SobreNosotros.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Sobre Nosotros";
}

<link href="c:\users\xcf\source\repos\rubiksmx\rubiksmx\wwwroot\css\site.css" rel="stylesheet" />

        <style>
    

    body {
        font-family: Arial, Helvetica, sans-serif;
        background: #272727;
    }

    * {
        box-sizing: border-box;
    }

    input[type=text], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=submit] {
        background-color: #04AA6D;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    .container {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
  
        </style>


<br /> <br /> <br /> <br /> <br /> 
<p align="center"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3591.9975255667337!2d-100.27884222386999!3d25.803655706868962!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8662933b78ced7e5%3A0x6799f872d652eb71!2sXCF%20S.A.%20de%20C.V.!5e0!3m2!1ses-419!2smx!4v1694449216730!5m2!1ses-419!2smx" width="700" height="500" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></p>



<body>

    <div class="container">
        <form action="/action_page.php">
            <label for="fname">First Name</label>
            <input type="text" id="fname" name="firstname" placeholder="Your name..">

            <label for="lname">Last Name</label>
            <input type="text" id="lname" name="lastname" placeholder="Your last name..">

            <label for="country">Country</label>
            <select id="country" name="country">
                <option value="australia">Australia</option>
                <option value="canada">Canada</option>
                <option value="usa">USA</option>
            </select>

            <label for="subject">Subject</label>
            <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

            <input type="submit" value="Submit">
        </form>
    </div>
</body>